### ISSUE TITLE
Some sources seem to be missing

### ISSUE THREAD

**Issue by s-iso** [rantonels/schwarzschild#1]
Hey there

I wanted to clean your project up a bit, but I stumbled across some source-errors. It seems like some sourcefiles are missing.

In particular, I can't find the function reference of "createShaderFromScriptElement", neither was I able to "getWebGlContext".

Would be nice if you could provide them, so I could make that code way more beautiful and performant :)

**Comment by rantonels** [comment]
I forgot to git add a folder containing a large set of helper functions that I'd shamelessly copied right from a WebGL tut. It should be up now.
